ETicaretWebApplication/Controllers/FavoritesController.cs
using ETicaret_Core.Entities;
using ETicaret_Data;
using ETicaretWebApplication.ExtensionMethods;
using Microsoft.AspNetCore.Mvc;

namespace ETicaretWebApplication.Controllers
{
    public class FavoritesController : Controller
    {
        private readonly ETicaret_Context _context;
        public FavoritesController(ETicaret_Context context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var favoriler = GetFavorites();
            return View(favoriler);
        }
        private List<Product> GetFavorites()
        {
            return HttpContext.Session.GetJson<List<Product>>("GetFavorites") ?? [];
        }

        public IActionResult Add(int ProductID)
        {
            var favoriler = GetFavorites();
            var product = _context.Products.Find(ProductID);
            if (product != null && !favoriler.Any(p => p.ID == product.ID))
            {
                favoriler.Add(product);
                HttpContext.Session.SetJson("GetFavorites",favoriler);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Remove(int ProductID)
        {
            var favoriler = GetFavorites();
            var product = _context.Products.Find(ProductID);
            if (product != null && !favoriler.Any(p => p.ID == product.ID))
            {
                favoriler.RemoveAll(i => i.ID == product.ID );
                HttpContext.Session.SetJson("GetFavorites", favoriler);
            }
            return RedirectToAction("Index");
        }

    }
}

ETicaretWebApplication/Views/Favorites/Index.cshtml
@model List<Product>
@{
    ViewData["Title"] = "Favorilerim";
}

<div class="text-center">
    <h1 class="display-4">Favorilerim</h1>
</div>

<section class="row">
    <div class="col-md-10">
        <div class="table-responsive">
        @if(Model.Any())
        {
            <table class="table table-hover table-striped">
                <tr>
                    <th></th>
                    <th>Ürün</th>
                    <th>Fiyat</th>
                    <th></th>
                </tr>
                <tbody>
                        @foreach(var item in Model)
                        {
                            <tr>
                                <td>
                                    <img src="/image_client/Products/@item.ID" alt="" height="37" />
                                </td>
                                <td>
                                    <a class="nav-link text-dark" href="/Products/Details/@item.ID">
                                        @item.Name    
                                    </a>
                                </td>
                                <td>
                                    @item.Price.ToString("c")
                                </td>
                                <td>
                                    <form asp-action="Add" asp-controller="Favorites">
                                        <input type="hidden" name="ProductID" value="@item.ID"/>
                                        <button class="btn btn-sm btn-danger" type="submit">
                                            <i class="bi bi-x-lg"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        }
                </tbody>
            </table>
        }
        else{
            <div class="container">
                <div class="alert alert-warning my-5">
                    <h3>Favorilerinizde Ürün Bulunmamaktadır !</h3>
                </div>
            </div>
        }
        </div>
    </div>
</section>